swagger: "2.0"
info:
  version: "0.0.1"
  title: RFC-6749 Authorization Server API
host: "localhost:2406"
# basePath prefixes all resource paths 
basePath: /oauth
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /token:
    # binds a127 app logic to a route
    x-swagger-router-controller: token-controller
    post:
      consumes: 
        - application/x-www-form-urlencoded
      description: 'Token Endpoint. The token endpoint is used by the client to obtain an access token by presenting its authorization grant or refresh token. The token endpoint is used with every authorization grant except for the implicit grant type (since an access token is issued directly).'
      parameters:
        - name: grant_type
          in: formData
          type: string
          enum:
            - authorization_code
            - password
            - client_credentials
            - refresh_token
          description: Value MUST be set to "authorization_code", "password", "client_credentials", "refresh_token".
        - name: refresh_token
          in: formData
          type: string
          description: REQUIRED when using grant_type "refresh_token". The refresh token issued to the client.
        - name: code
          in: formData
          type: string
          description: REQUIRED if the grant_type is authorization_code. The authorization code received from the authorization server.
        - name: redirect_url
          in: formData
          type: string
          description: REQUIRED, if the "redirect_uri" parameter was included in the authorization request as described in Section 4.1.1, and their values MUST be identical.
        - name: client_id
          in: formData
          type: string
          description: The client identifier as described in Section 2.2
        - name: username
          in: formData
          type: string
          description: REQUIRED when grant_type is set to password. Value MUST be set to "password".
        - name: password
          in: formData
          type: string
          description: REQUIRED when grant_type is set to password. The resource owner username.
        - name: scope
          in: formData
          type: string
          description: OPTIONAL. The scope of the access request as described by Section 3.3.
        - name: Authorization
          description: Authorization token
          type: string
          in: header
          required: false
      responses:
        "200":
          description: 'If the access token request is valid and authorized, the authorization server issues an access token and optional refresh token as described in Section 5.1.'
          schema:
            $ref: "#/definitions/AccessTokenResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /authorization:
    # binds a127 app logic to a route
    x-swagger-router-controller: authorization-controller
    get:
      description: 'Authorization Endpoint. The authorization endpoint is used to interact with the resource owner and obtain an authorization grant. The authorization server MUST first verify the identity of the resource owner. The way in which the authorization server authenticates the resource owner (e.g., username and password login, session cookies) is beyond the scope of this specification. The authorization endpoint is used by the authorization code grant type and implicit grant type flows.'
      parameters:
        - name: response_type
          description: 'REQUIRED. Value MUST be set to "token". "code".'
          type: string
          enum:
            - code
            - token
          in: query
          required: true
        - name: client_id
          description: 'REQUIRED. The client identifier as described in Section 2.2'
          type: string
          in: query
          required: true
        - name: redirect_uri
          description: 'OPTIONAL. As described in Section 3.1.2.'
          type: string
          in: query
          required: false
        - name: scope
          description: 'OPTIONAL. The scope of the access request as described by Section 3.3'
          type: string
          in: query
          required: false
        - name: state
          description: 'RECOMMENDED. An opaque value used by the client to maintain state between the request and callback. The authorization server includes this value when redirecting the user-agent back to the client. The parameter SHOULD be used for preventing cross-site request forgery as described in Section 10.12.'
          type: string
          in: query
          required: false
      responses:
        # responses may fall through to errors
        "302":
          description: Found
          headers:
            access_token:
              type: string
            token_type:
              type: string
            expires_in:
              type: number
            scope:
              type: string
            code:
              type: string
            state:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  AccessTokenResponse:
    required:
      - access_token
      - token_type
      - expires_in
    properties:
      access_token:
        type: string
        description: 'REQUIRED. The access token issued by the authorization server.'
      token_type:
        type: string
        description: 'REQUIRED. The type of the token issued as described in Section 7.1. Value is case insensitive.'
      expires_in:
        type: number
        description: 'RECOMMENDED. The lifetime in seconds of the access token. For example, the value "3600" denotes that the access token will expire in one hour from the time the response was generated. If omitted, the authorization server SHOULD provide the expiration time via other means or document the default value.'
      refresh_token:
        type: string
        description: 'OPTIONAL. The refresh token, which can be used to obtain new access tokens using the same authorization grant as described in Section 6.'
      scope:
        type: string
        description: 'OPTIONAL, if identical to the scope requested by the client; otherwise, REQUIRED. The scope of the access token as described by Section 3.3.'
  ErrorResponse:
    required:
      - error
    properties:
      error:
        type: string
        description: "REQUIRED. A single ASCII [USASCII] error code from the following: invalid_request, unauthorized_client, access_denied, unsupported_response_type, invalid_scope, invalid_scope, server_error, temporarily_unavailable"
        enum: 
          - invalid_request
          - unauthorized_client
          - access_denied
          - unsupported_response_type
          - invalid_scope
          - server_error
          - temporarily_unavailable
      error_description:
        description: "OPTIONAL. Human-readable ASCII [USASCII] text providing additional information, used to assist the client developer in understanding the error that occurred."
        type: string
      error_uri:
        description: "OPTIONAL. A URI identifying a human-readable web page with information about the error, used to provide the client developer with additional information about the error."
        type: string



